---
openapi: 3.1.0
components:
  schemas:
    ExchangeRequest:
      type: object
      required:
        - code
      properties:
        code:
          type: string
    GraphUser:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        picture:
          type: string
        role:
          $ref: "#/components/schemas/Role"
    Instant:
      type: string
      format: date-time
      examples:
        - 2022-03-10T16:15:50Z
    PosToken:
      type: object
      properties:
        expiresAt:
          $ref: "#/components/schemas/Instant"
        expiresAtMs:
          type: integer
          format: int64
        expiresInSeconds:
          type: integer
          format: int64
        merchantId:
          type: string
    Role:
      type: object
      properties:
        value:
          type: string
        id:
          type: string
        system:
          type:
            - string
            - "null"
        token:
          type: string
    TokenRevokeResponse:
      type: object
      properties:
        success:
          type: boolean
  securitySchemes:
    SecurityScheme:
      description: Authentication
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /session/authenticate:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json: {}
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Authenticate
      tags:
        - User Session Resource
      security:
        - SecurityScheme: []
  /session/complete:
    get:
      parameters:
        - name: state
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GraphUser"
      summary: Complete
      tags:
        - User Session Resource
  /session/exchange:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExchangeRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GraphUser"
        "400":
          description: Bad Request
      summary: Exchange
      tags:
        - User Session Resource
  /session/me:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GraphUser"
      summary: User
      tags:
        - User Session Resource
  /session/user/create:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GraphUser"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GraphUser"
        "400":
          description: Bad Request
      summary: Add User
      tags:
        - User Session Resource
  /shopify/authorize:
    get:
      parameters:
        - name: userId
          in: query
          schema:
            type: string
        - name: shop
          in: query
          schema:
            type: string
        - name: user_id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json: {}
      summary: Authorize
      tags:
        - Shopify Token Resource
  /shopify/callback:
    get:
      parameters:
        - name: client_id
          in: query
          schema:
            type: string
        - name: code
          in: query
          schema:
            type: string
        - name: merchant_id
          in: query
          schema:
            type: string
        - name: state
          in: query
          schema:
            type: string
        - name: hmac
          in: query
          schema:
            type: string
        - name: host
          in: query
          schema:
            type: string
        - name: shop
          in: query
          schema:
            type: string
        - name: timestamp
          in: query
          schema:
            type: string
        - name: error
          in: query
          schema:
            type: string
        - name: error_description
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json: {}
      summary: Callback
      tags:
        - Square Token Resource
  /square/refresh:
    post:
      parameters:
        - name: merchant_id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PosToken"
      summary: Refresh Token
      tags:
        - Square Token Resource
  /square/revoke:
    post:
      parameters:
        - name: merchant_id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenRevokeResponse"
      summary: Revoke Token
      tags:
        - Square Token Resource
  /square/token:
    post:
      parameters:
        - name: merchant_id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PosToken"
      summary: Token
      tags:
        - Clover Token Resource
    get:
      parameters:
        - name: merchant_id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PosToken"
      summary: Status
      tags:
        - Square Token Resource
info:
  title: Graph User Session API
  version: 1.0.0-SNAPSHOT
  description: Security API to manage user sessions and tokens
servers:
  - url: http://localhost:8080
    description: Auto generated value
  - url: http://0.0.0.0:8080
    description: Auto generated value
