name: Pull Request - CI build

on:
  pull_request:

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Cleanup
        run: |
          rm -rf node_modules
          npm cache clean --force
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
