name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Cleanup
        run: |
          rm -rf node_modules
          npm cache clean --force
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build

  fly-deploy:
    needs: npm-build
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}